config/routes.rb
Rails.application.routes.draw do
  get 'reward', to: 'logs#reward', as: 'reward'

  resources :tasks do
    resources :logs
  end
  root to: 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :task

  before_create :decide_if_reward_given

  # 20% chance of getting reward.
  #`rand` returns random number between 0 and 1
  def decide_if_reward_given
    if rand < 0.2
      self.gave_reward = true
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :logs

  enum time_of_day: {
    morning: 0,
    afternoon: 1,
    evening: 2,
    any: 3
  }

  enum frequency: {
    daily: 0,
    semi_weekly: 1,
    weekly: 2,
    semi_monthly: 3,
    monthly: 4
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def show
  end

  def index
    @logs = Task.includes(:logs).find(params[:task_id]).logs.all
  end

  def new
    @task = Task.find(params[:task_id])
    @log = @task.logs.new
  end

  def create
    log = Task.find(params[:task_id]).logs.new(log_params)
    if log.save
      log_redirect_path = log.gave_reward? ? reward_path : root_path
      redirect_to log_redirect_path
    end
  end

  def reward
  end

  private

  def log_params
    params.require(:log).permit(:notes)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    if task.save
      redirect_to root_path
    else
      render StandardError
    end
  end

  def show
    @task = Task.find(params[:id])
    @logs = @task.logs
  end

  def index
    @tasks = Task.includes(:logs).all
  end

  private

  def task_params
    params.require(:task).permit(:name,
                                 :details,
                                 :required_time_in_minutes,
                                 :time_of_day,
                                 :frequency)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RabbitRewards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main">  
      <%= yield %>
    </div>
  </body>
</html>

app/views/logs/index.html.erb
<h1>Logs#index</h1>
<p>Find me in app/views/logs/index.html.erb</p>

app/views/logs/new.html.erb
<div class="container">
  <div class="card">
    <div class="container">
      <h1>New Log For <%= @task.name %></h1>
      <%= form_for [@task, @log] do |f| %>
        <h4>How was it today?</h4>
        <%= f.text_area :notes %><br/>
        <%= f.submit "Log It", class:'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</div>

app/views/logs/reward.html.erb
<div class="container">
  <div class="card">
    <h1>Nice Work! Give your self a reward today</h1>
    <%= link_to "home", root_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/logs/show.html.erb
<h1>Logs#show</h1>
<p>Find me in app/views/logs/show.html.erb</p>

app/views/tasks/index.html.erb
<div class="container">
  <h1>Tasks</h1>

    Stay consistent with your habits
    Every time you do the thing, there's a 20% chance that
    you can reward yourself for being awesome.
    <br/>
    This app uese reward prediction error.
    <br/> <br/>
    Learn more about reward prediction error in the time stamp on <%= link_to "this video", "https://youtu.be/vA50EK70whE?t=3003" %> (00:50:03)

    <br/><br/><br/>
  <%= link_to "New Task", new_task_path, class: 'btn btn-primary' %>
  <br/>
  <div class="card">

    <table class="table table-dark">
      <tr>
        <th scope="col">Log</th>
        <th scope="col">Name</th>
        <th scope="col">Dur.</th>
        <th scope="col">Time
        <th scope="col">Log'd</th>
        <th scope="col">Rewards</th>
      </tr>
      <% @tasks.each do |task| %>
          <tr>
            <th scope="row"><%= link_to "+", new_task_log_path(task), class: 'btn btn-success' %></th>
            <td><%= link_to task.name.titleize, task_path(task) %></td>
            <td><%= task.required_time_in_minutes %></td>
            <td><%= task.time_of_day %><br/>
            <%= task.frequency %></td>
            <td><%= task.logs.count %></td>
            <td><%= task.logs.select {|l| l.gave_reward? }.count %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Create a new task</h1>
  <div class="card">
    <%= form_for @task do |f| %>
        <h3> Task Name  </h3>
        <%= f.text_field :name %>
        <br/>
        <h3> Details  </h3>
        <%= f.text_area :details %>
        <br/>
        <h3> Required time (in minutes)  </h3>
        <%= f.number_field :required_time_in_minutes, in: 10..300, step: 5 %>
        <br/>
        <h3> Time of day</h3>
        <%= f.select :time_of_day, Task.time_of_days.keys %>
        <br/>
        <h3>How Often?</h3>
        <%= f.select :frequency, Task.frequencies.keys %>
        <br/>
        <br/>
      <%= f.submit "Create Task", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>